### ISSUE TITLE
MySQL additional DB utf-8 issue 

### ISSUE THREAD

**Issue by sime-k** [bigpresh/Dancer-Plugin-Database#58]
Utf-8 works with default database but when i use additional one it returns.

Example:
config.yml
```
charset: "utf-8"

plugins:
    Database:
      driver: 'mysql'
      database: 'data'
      host: 'localhost'
      username: 'user'
      password: 'pass'
      connections:
        stats:
              driver: 'mysql'
              database: 'data'
              host: 'localhost'
              username: 'user'
              password: 'pass'    
```
data: {NAME=>ščćđ}

Dancer
```
	my $test = database->quick_select('RECORDINGS', {ID=>'174309663'});
	return to_json $test;
        # returns {NAME=>ščćđ}

	my $test = database('stats')->quick_select('RECORDINGS', {ID=>'174309663'});
	return to_json $test;
        # returns {NAME=>????}
